version: '3'
services:
  strapi:
    build: .
    ports:
      - '1337:1337'
    volumes:
      # Monte le dossier local pour la persistance des uploads
      - ./public/uploads:/opt/app/public/uploads
    environment:
      NODE_ENV: production